# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

# define the VM image I want to use for my build
pool:
  vmImage: 'Ubuntu 16.04'

# define variables to use during the build
variables:
  projectFolder: 'src/angular'
  buildOutputFolder: 'src/angular/dist/angular'

# define the steps of the build
steps:

## Install Angular CLI
- script: |
    npm install -g @angular/cli@13.2.5
  displayName: 'Install Angular CLI'

## Build Angular project
- script: |
    cd $(projectFolder)
    ng build
  displayName: 'Angular Build'

## Copy the client to the staging directory
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(buildOutputFolder)' 
    contents: '**/*' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true

## Archive the files into a zip file for publishing
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: $(Build.ArtifactStagingDirectory)
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    includeRootFolder: false

## Publish the zip file
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
