# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

# define the VM image I want to use for my build
pool:
  vmImage: 'Ubuntu-latest'

# define variables to use during the build
variables:
  projectFolder: 'src/angular'
  buildOutputFolder: 'src/angular/dist/angular'

steps: 
- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Install Node.js'

- script: npm install -g @angular/cli@13.2.5
  displayName: 'Install Angular CLI'

- task: UseNode@1
  inputs:
    version: '16.x'
    checkLatest: true
  displayName: 'Use Node.js version'

- script: ng build
  displayName: 'Angular Build'
