# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

# define the VM image I want to use for my build
pool:
  vmImage: 'Ubuntu-latest'

# define variables to use during the build
variables:
  projectFolder: 'src/angular'
  buildOutputFolder: 'src/angular/dist/angular'

steps: 
- task: NodeTool@0
  inputs:
    versionSpec: '16.0'
  displayName: 'Install Node.js'
 
- task: Npm@1  
  displayName: 'Angular CLI 13.2.5'  
  inputs:  
    command: custom  
    verbose: false  
    customCommand: 'install -g @angular/cli@13.2.5'
 
- task: Npm@1  
  displayName: 'npm install'  
  inputs:
    command: custom  
    customCommand: 'install file:custom-angular-lib.tgz --legacy-peer-deps'  
   
- task: Npm@1  
  displayName: Build  
  inputs: 
    command: custom  
    verbose: false  
    customCommand: 'run build'